onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - bufferutil
  - esbuild
  - unrs-resolver
  - utf-8-validate

overrides:
  diff@<8.0.3: '>=8.0.3'
  esbuild@<=0.24.2: '>=0.25.0'
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'
  tar@<=7.5.2: '>=7.5.3'
  undici@<5.29.0: '>=5.29.0'
  undici@>=4.5.0 <5.28.5: '>=5.28.5'
