packages:
  - ./

allowBuilds:
  bufferutil: false
  esbuild: false
  unrs-resolver: false

blockExoticSubdeps: true

minimumReleaseAge: 10080 # 7 days in minutes

minimumReleaseAgeExclude:
  - pnpm@11.24.0

overrides:
  vercel: ~58.4.4
  semver: '>=7'
  undici@<6.27.0: ^6.27.0
  '@tootallnate/once@<2.0.1': ^2.0.1
  ajv@>=7.0.0-alpha.0 <8.18.0: ^8.18.0
  esbuild@>=0.27.3 <0.28.1: ^0.28.1
  js-yaml@>=4.0.0 <4.3.0: ^4.3.0
  js-yaml@>=4.0.0 <4.3.1: ^4.3.1
  js-yaml@>=4.0.0 <=4.1.1: ^4.2.0
  minimatch@>=10.0.0 <10.2.1: ^10.2.1
  minimatch@>=10.0.0 <10.2.3: ^10.2.3
  path-to-regexp@>=4.0.0 <6.3.0: ^6.3.0
  path-to-regexp@>=8.0.0 <8.4.0: ^8.4.0
  smol-toml@<1.6.1: ^1.6.1
  tar@<7.5.8: ^7.5.8
  tar@<=7.5.10: ^7.5.11
  tar@<=7.5.15: ^7.5.16
  tar@<=7.5.16: ^7.5.17
  tar@<=7.5.17: ^7.5.18
  tar@<=7.5.18: ^7.5.19
  tar@<=7.5.20: ^7.5.21
  tar@<=7.5.9: ^7.5.10

trustPolicy: no-downgrade
