packages:
  - ./

allowBuilds:
  bufferutil: false
  esbuild: false
  unrs-resolver: false

blockExoticSubdeps: true

minimumReleaseAge: 10080 # 7 days in minutes

minimumReleaseAgeExclude:
  - pnpm@12.8.2

overrides:
  '@tootallnate/once@<2.0.1': ^2.0.1
  ajv@>=7.0.0-alpha.0 <8.18.0: ^8.18.0
  js-yaml@>=4.0.0 <4.3.2: ^4.3.2
  minimatch@>=10.0.0 <10.2.3: ^10.2.3
  path-to-regexp@>=4.0.0 <6.3.0: ^6.3.0
  path-to-regexp@>=8.0.0 <8.4.0: ^8.4.0
  semver: '>=7'
  smol-toml@<=1.7.0: ^1.7.1
  tar@<=7.5.20: ^7.5.21
  undici: '>=6'

trustPolicy: no-downgrade
