onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - bufferutil
  - esbuild
  - unrs-resolver
  - utf-8-validate

overrides:
  '@eslint/js': '>=10.0.0'
  '@stylistic/eslint-plugin': '>=5.0.0'
  ajv@<8.18.0: '>=8.18.0'
  diff@<8.0.3: '>=8.0.3'
  esbuild@<=0.24.2: '>=0.27.0'
  eslint: '>=10.0.0'
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'
  seroval@<1.4.1: '>=1.4.1'
  tar@<7.5.8: '>=7.5.8'
  undici@<5.29.0: '>=5.29.0'
  '@eslint/eslintrc>ajv': ^6.12.4
  eslint>ajv: ^6.12.4
  minimatch@<10.2.1: '>=10.2.1'
  '@eslint/eslintrc>minimatch': '^3.1.2'
